### PR TITLE
Added the /ext and /clearinventory commands

### PR DESCRIPTION
**Pull request by nounoursheureux**

### CODE REVIEW

**Comment by tonibm19** [comment]
Thanks

**Comment by mathias-github** [comment]
There is already a clear inventory-command in Core, which has support for clearing both your own inventory and other players' inventories.

**Comment by nounoursheureux** [comment]
You're right, I didn't notice this

**Comment by tonibm19** [comment]
Well, anyway, essentials-core commands will be reorganized (when I finish exams)

**Pull request merged**
