### PR TITLE
Added sqlite support

### LINKED ISSUE #25: SQLite rewrite
Rewrite jails, homes and warps to use SQLite.
I don't know SQLite, so I won't do it soon, maybe some day if I learn.
Any volunteer?

### PR DESCRIPTION
**Pull request by scribblemaniac**
Currently this sqlite database is used for managing warps, homes, and jails. Everything has been tested and appears to be working correctly. Almost everything behaves the same as it did before. The only noticeable change to the functioning of the plugin was to the jails. I added the feature to teleport a user back to the position they were at when they were initially jailed when they are unjailed. I believe this is how the old essentials plugin behaved and it was easiest to implement it while designing the new database structure. Just let me know if there's something that needs to be improved upon before this can be pulled.

Closes #25

### CODE REVIEW

**Comment by tonibm19** [comment]
I love you. XD. Thanks!
Im dont know sqlite but xoft can probably revise it.

**Comment by tonibm19** [comment]
@madmaxoft

**Comment by madmaxoft** [comment]
I'd have preferred if the DB code was split away from the other application logic. As it is now, the functions are big globs of code that does everything and is very difficult to read.

Also the indentation seems off at places.

**Comment by scribblemaniac** [comment]
I have cleaned things up quite a bit and I think you will like it a lot more now.

Sorry for the indention issues, I've been having trouble finding a good Lua editor. Any suggestions?

**Comment by madmaxoft** [comment]
I use ZeroBrane Studio. It's a whole IDE that even has support for Cuberite-specific code completion and can debug the plugin while it's running in the server. There's a guide for setting it up: http://apidocs.cuberite.org/SettingUpZeroBrane.html

**Comment by madmaxoft** [comment]
The code is better, but still not isolated enough. If we decide to change the DB schema, we'll still need to go into the individual command handlers and change them.
Normally, the database layer would wrap higher-level constructs into function calls - for example, `getHomeCoords(a_PlayerUUID, a_HomeName)` would return the coords of the player's home, or nil on error. It would be up to the DB layer to decide how and where to store the information. `

Also note that the Player UUID is always a valid value, you can safely use it as the DB key directly - no need for a separate `userId` column and translation table.
As an improvement for jailing, you could consider adding yet another DB table, "pending jail", so that admins can jail a player who has not visited a server yet (and therefore has no UUID stored in the cMojangAPI cache), simply by storing the player name and checking that table on player login. This is, however, optional for this PR.

**Comment by madmaxoft** [comment]
Here's how I implemented the sqlite support in the Gallery plugin, for inspiration: https://github.com/cuberite/gallery/blob/master/Storage_SQLite.lua . Have a look at the `SQLite:LoadXYZ()` functions as an example of the interface.

**Comment by scribblemaniac** [comment]
Thanks for the IDE suggestion, I will be sure to check it out.

I will consider your high-level handlers suggestion, because it does have some benefits. I especially like the ability to easily check preconditions. However I can't help but feel that it is a little excessive. There are very few good reasons to change the database schema in a way that wouldn't mean changing the arguments or function name of your high-level functions, and subsequently all of the function calls that you attempted to avoid changing. The functions also come at the the cost of additional overhead and an obscured view of how your variables are actually being used.

The `userId` is a necessary column. Using strings for primary / foreign keys will be slower because of longer comparison operations. Much more importantly, they aren't necessarily unique, which is a requirement for how I would be using them. A quote from the cuberite source for the Player:GetUUID function:

> Returns the UUID (short format) that has been read from the client, or empty string if not available.

Immediately there are two issues here. The first is that the function can return an empty string, which could certainly occur for multiple different players (most likely as a result of unmigrated accounts). The second is that the UUID is apparently retrieved from the client, meaning it is not unreasonable to think that it could be spoofed. Also if I implement the pending jail suggestion that you had (which I probably won't until this gets pulled), then that will also result in a null / empty uuid which is again not unique. The userid will allow for greater flexibility in the future as well if Mojang decides to change things.

**Comment by madmaxoft** [comment]
I still don't see any real disadvantages to using high-level handlers. It promotes encapsulation, hides internal implementation and even makes the client code more readable. The function call overhead is really minimal, and it's much less than creating a few tables for your calls.

As for the UUID, that comes either directly from the server (when in offline mode, UUIDs are generated by hashing the lowercased playername) or from Mojang servers (when in online mode) which kinda guarantee uniqueness because they use them to identify accounts.
The `cPlayer:GetUUID()` function only returns an empty string if the player doesn't have a `cClientHandle` attached to it - which is being considered for bots in the future, but currently it doesn't happen.

You won't get much speedup from using integral keys if you still have to look up that key from a string value.

**Comment by scribblemaniac** [comment]
If you really want these handlers so badly, I'll implement them when I get a chance.

Sorry about the UUID confusion. I was just remembering a while back that there were some issues with legacy accounts not getting UUIDs but some testing reveals that has been fixed. I'll get rid of the UUID if its not necessary.

**Comment by madmaxoft** [comment]
Sorry, I didn't want to sound so forceful. I'm just interested in the arguments supporting your opinion. As they say, you always learn something new from other people :)

**Comment by scribblemaniac** [comment]
I'm all for discussing things, everyone can learn something from a constructive argument. In this case however you're probably right, I just hate admitting that I'm wrong :stuck_out_tongue:

**Comment by scribblemaniac** [comment]
Hey I am really sorry for the lack of updates. I have decided that it would be best to split my code up into two separate files. One would hold essentials related database commands (things like `GetHomeLocation` or `AddJail` functions). The second file would contain functions for direct database manipulation (things like `AddTable` or `SetValue`). I will make this second file its own project so that others can use it to make database support easier for their plugins and so that updates to this "library" can be applied to a central location.

I've been working on refactoring the code to reflect this change in approach. I have modified the design of the program a bit to better fit, and have been adding significantly more things for error handling. Unfortunately I have been very busy lately and have been unable to make nearly as much progress with these changes as I would like to. Looking ahead seems to indicate that things will only get worse for me in the near future. Because of this, I am closing this PR. I will open a new one when I am ready, which sadly may be a while.

**Comment by tonibm19** [comment]
No problem, thanks!

**Pull request closed without merging**
