### PR TITLE
Added /depth command

### PR DESCRIPTION
**Pull request by scribblemaniac**

### CODE REVIEW

**Comment by tonibm19** [comment]
I think I will wait till https://github.com/mc-server/Essentials/pull/34 is merged, to avoid problems

**Comment by scribblemaniac** [comment]
Okay

**Comment by tonibm19** [comment]
Thanks! :)

**Comment by tonibm19** [comment]
Can you resolve the conflicts and we merge?

**Comment by scribblemaniac** [comment]
Rebased and ready to go.

**Comment by tonibm19** [comment]
You're changing HandleLocate command to HandleGetPos command.

**Comment by scribblemaniac** [comment]
Oops, I must've misread the changes. Fixed.

**Comment by tonibm19** [comment]
Thanks!

**Pull request merged**
